rules:
  - organization_list:
      - org1
      - org2
    parameters:
    - tag_filter: "."
      keep_n_tags: "5"
      keep_tags_younger_than: "1y"
  - organization_list:
      - org3
    parameters:
    - tag_filter: "."
      keep_n_tags: "15"
      keep_tags_younger_than: "1y"

default_rule:
  enabled: True
  parameters:
    - tag_filter: "."
      keep_n_tags: "10"
      keep_tags_younger_than: "2y"
