# Default values for pruner.
# This is a YAML-formatted file.

failedJobsHistoryLimit: 1

image: quay.io/gsciorti/quay-tags-pruner:v0.3
imagePullPolicy: IfNotPresent

namespace: gsciorti-quay-tags-pruner

schedule: 30 22 * * *
startingDeadlineSeconds: 200
successfulJobsHistoryLimit: 3
cronJobApiVersion: batch/v1


# Env variables
debug: True
dryRun: False
quayAppToken: "Bearer Sh6WkuTy030DWag4nSmDJ2ZugtPKdYfYsDuypwtc"
quayUrl: "instance-quay-quay-registry.apps.lab01.gpslab.club"

