# Default values for pruner.
# This is a YAML-formatted file.

failedJobsHistoryLimit: 1

image: quay.io/amigliet/quay-tags-pruner:v0.2
imagePullPolicy: IfNotPresent

namespace: demo-cronjobs

schedule: 30 22 * * *
startingDeadlineSeconds: 200
successfulJobsHistoryLimit: 3
cronJobApiVersion: batch/v1
suspend: false


# Env variables
debug: False
dryRun: False
quayAppToken: "<TOKEN>"
quayUrl: "example-quay-quay-registry.apps.clustername.basedomain.com"
quayApiTimeout: 60.0

# Prometheus role parameter
prometheusRuleDeploy: true
prometheusRuleAlertName: "QuayTagsPrunerJobStatusFailed"
prometheusRuleAlertSeverity: "error"
