# Default values for pruner.
# This is a YAML-formatted file.

# Config file used to generate configmap/quay-tags-pruner-config
#configFile: "config.yaml"

cronJobApiVersion: batch/v1

failedJobsHistoryLimit: 1

image: quay.io/amigliet/quay-tags-pruner:v0.2
imagePullPolicy: IfNotPresent

namespace: demo-cronjobs

schedule: 30 22 * * *
startingDeadlineSeconds: 200
successfulJobsHistoryLimit: 3


# Env variables
debug: False
dryRun: False
quayAppToken: "<TOKEN>"
quayUrl: "example-quay-quay-registry.apps.clustername.basedomain.com"

# Prometheus role parameter
prometheusRuleDeploy: true
prometheusRuleAlertName: "QuayTagsPrunerJobStatusFailed"
prometheusRuleAlertSeverity: "error"
