apiVersion: v1
data:
  config.yaml: |-
{{ default "config.yaml" .Values.configFile | .Files.Get | nindent 4 }}
kind: ConfigMap
metadata:
  name: quay-tags-pruner-config
  namespace: {{ .Values.namespace }}
