apiVersion: {{ .Values.cronJobApiVersion }}
kind: CronJob
metadata:
  name: quay-tags-pruner
  namespace: {{ .Values.namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          activeDeadlineSeconds: 500
          containers:
          - name: quay-tags-pruner
            env:
            - name: DEBUG
              value: "{{ .Values.debug }}"
            - name: DRY_RUN
              value: "{{ .Values.dryRun }}"
            - name: QUAY_URL
              value: "{{ .Values.quayUrl }}"
            envFrom:
            - secretRef:
                name: quay-tags-pruner-token
            image: {{ .Values.image }}
            imagePullPolicy:  {{ .Values.imagePullPolicy }}
            volumeMounts:
            - mountPath: /opt/conf
              name: quay-config
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: quay-tags-pruner-config
            name: quay-config
  schedule: {{ .Values.schedule }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
