---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: quay-pruner-instance0-subscription
  namespace: quay-pruner
  labels:
    app: quay-tags-pruner
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: deploy/rhacm/app-samples/instance0
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: quay-pruner/quay-pruner-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: quay-pruner-placementrule
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: quay-pruner-instance1-subscription
  namespace: quay-pruner
  labels:
    app: quay-tags-pruner
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: deploy/rhacm/app-samples/instance1
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: quay-pruner/quay-pruner-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: quay-pruner-placementrule
